# Render deployment configuration for backend
version: 1
services:
  - type: web
    name: campo-vida-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
